version: "3"
services:
  conditional:
    build: .
    container_name: conditional
    depends_on:
      - conditional-postgres
    ports:
      - "127.0.0.1:8080:8080"
  conditional-postgres:
    image: docker.io/postgres
    container_name: conditional-postgres
    environment:
      POSTGRES_PASSWORD: fancypantspassword 
      POSTGRES_USER: conditional
      POSTGRES_DATABASE: conditional
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

